# This is a basic workflow to help you get started with Actions

name: TestCache

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cache first
        with:
          path: ./build/**
          key: ${{ github.sha }}

  use-build-cache: 
    runs-on: ubuntu-latest
    needs: build-cache

    steps:
      - uses: actions/cache@v2
        name: Use Cache from previous step
        with:
          path: ./build/**
          key: ${{ github.sha }}

      - run: cat ./build/a.txt

